name: Flutter CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: windows-latest  # ← ИЗМЕНИТЕ НА windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'  # Актуальная стабильная версия
        channel: 'stable'
    
    - name: Verify Flutter version
      run: flutter --version
    
    - name: Install dependencies
      run: flutter pub get
      working-directory: ./flutter_application
    
    - name: Analyze
      run: flutter analyze
      working-directory: ./flutter_application
    
    - name: Run tests
      run: flutter test
      working-directory: ./flutter_application
